#!/usr/bin/with-contenv sh
echo "creating watch folders"
mkdir -p $RPC_WATCH_MUSIC_FOLDER
mkdir -p $RPC_WATCH_TV_HD_FOLDER
mkdir -p $RPC_WATCH_TV_UHD_FOLDER
mkdir -p $RPC_WATCH_MOVIES_HD_FOLDER
mkdir -p $RPC_WATCH_MOVIES_UHD_FOLDER
